### ISSUE TITLE
aioprocessing is awesome, and i have an issue report

### ISSUE THREAD

**Issue by openalmeida** [dano/aioprocessing#12]
Hi,

i am come from ``http://stackoverflow.com/questions/24687061`` of your topic,
then use `pip` to got this great lib with version 0.0.3 (same as git head i think).

and found your demo of `example2`  will raise exception like below

```Python

...  __aexit__() takes 1 positional argument but 4 were given ...

... blah ... blah ...

 TypeError: 'NoneType' object is not iterable
```

i changed `aioprocessing/locks.py::95`

`def __aexit__(self):` 
to
 `def __aexit__(self, *args, **kwargs):`

it seems ok at least for me,
if issue confirmed would you do a pip source update (1.0.0 maybe :+1: ) please.

thanks a lot.

**Comment by dano** [comment]
@openalmeida Thanks for the report. You're right, I'll get it fixed and get a new version uploaded to PyPI as soon as I can.

**Comment by dano** [comment]
Just committed the fix. Thanks again for reporting!

**Comment by dano** [comment]
I also pushed a new versoin (1.0.0) to PyPI.
