### ISSUE TITLE
Please provide a way to pass asyncio loop to all objects

### ISSUE THREAD

**Issue by jabdoa2** [dano/aioprocessing#20]
Currently we cannot use aioprocessing in unit tests because we cannot pass our test loop to the objects. Is there a way this can be added?

**Comment by jabdoa2** [comment]
Ah I see. You can pass it on call also. Works that way. This is just a bit inconsistent with all the asyncio.Queue/Event objects which take the loop in their constructor

**Comment by asvetlov** [comment]
The explicit loop is considered deprecated anyway.

**Comment by hellysmile** [comment]
@jabdoa2 what Python version are You using?

**Comment by jabdoa2** [comment]
3.4 to 3.6. See https://groups.google.com/forum/#!topic/mpf-users/omWVIaroykQ

**Comment by dano** [comment]
I'm going to close this since there are alternative ways to do this, and explicitly passing the loop is considered deprecated for the core `asyncio` objects.
