### ISSUE TITLE
Deadlock when canceling coro_get on a AioQueue

### ISSUE THREAD

**Issue by jabdoa2** [dano/aioprocessing#21]
Maybe I'm doing something wrong. When i cancel a coro_get() future my process will hang on exit. Is that a known issue? Code looks like this:

```
    @asyncio.coroutine
    def _poll_events(self):
        while True:
            events = yield from self.event_queue.coro_get(loop=self.machine.clock.loop)
            self.process_events(events)

    @asyncio.coroutine
    def start(self):
        """Start listening for switches."""
        self.event_task = self.machine.clock.loop.create_task(self._poll_events())
        self.event_task.add_done_callback(self._done)

    def stop(self):
        """Stop proc."""
        if self.event_task:
            self.event_task.cancel()
            self.event_task = None
```

After that the process will never exit. I can work around this by returning a magic value in my queue and have _poll_events return instead but that does not look very nice. Any thoughts?

**Comment by dano** [comment]
The call to `coro_get` is delegating to a call to `Queue.get` that runs in a background worker pool thread, which can't be cancelled. So, while you're able to cancel the `_poll_events` coroutine, the underlying `Queue.get()` call is not cancelled. That leaves the worker thread waiting, which prevents the process from exiting. Using a sentinel (magic) value to kill the loop waiting for items in the queue is the right way to shut it down.

**Comment by jabdoa2** [comment]
Shouldn't that be documented? I understand this as you explain it. However, this is kind of unexpected for me as a user.

**Comment by dano** [comment]
Hmm, I can probably add a note in the README reminding users that cancellation of the coroutine wrappers doesn't guarantee cancellation of the underlying work. Reopening until I get around to doing that.

**Comment by dano** [comment]
Added a note to the readme about this.
