### ISSUE TITLE
New release is required to support Python 3.7.0

### ISSUE THREAD

**Issue by hellysmile** [dano/aioprocessing#22]
Python 3.7.0 was just released https://docs.python.org/3.7/whatsnew/3.7.html

https://github.com/dano/aioprocessing/pull/16/files fixed Python 3.7.0+ support

Can new release be pushed to https://pypi.org/ ?

**Comment by dano** [comment]
Done: https://pypi.org/project/aioprocessing/1.0.1/

**Comment by hellysmile** [comment]
thnx!!!!
