### ISSUE TITLE
Way to terminate a hanging process?

### ISSUE THREAD

**Issue by Tigerism** [dano/aioprocessing#23]
Is it possible to detect whether a process is taking too long to execute the code, and then terminate it, maybe through a timeout?

**Comment by dano** [comment]
You would do this the same when you'd do it if you were using `multiprocessing` directly. If you're using an `AioProcess`, you can call `terminate()` on it to kill the process. There's nothing built into `multiprocessing` to set a timeout, so you'd have to set that up yourself.

If you're using `AioPool`, you can't kill a individual worker in the pool, nor is there a way to set a timeout on how long a particular item you give the pool can take. You'd have to do your own co-operative implementation, where you have a hook in the method you're passing to the pool that allows you to interrupt it, and then flip whatever bit you decide to use to activate the hook after your timeout expires.
