### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.md'

### ISSUE THREAD

**Issue by Farhan958** [dano/aioprocessing#26]
Hi,
When i try to install keyboard module I have following problem:

Traceback (most recent call last):
  File "keyboard-0.13.2\setup.py", line 15,
 in <module>
    last_version = re.search('(\d+(?:\.\d+)+)', open('CHANGES.md').read()).group
(1)
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.md'

Python 3.7.1

**Comment by dano** [comment]
I think you filed this to the wrong project.
