### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by tejasmanohar** [dano/aioprocessing#4]
The last commit on this project is from July '15. While I don't usually judge a project's stability by how frequently it's being updated, since the README says 
>This project is currently in alpha stages, and likely has bugs. Use at your own risk. (I do appreciate bug reports, though :).

I thought I'd ask if this project is still being maintained.

**Comment by dano** [comment]
I'm still maintaining it, there just hasn't been much need for updates.

I put that note in the README when I wrote the initial version, but now that it's gotten almost a couple of years of use, it seems to have been proven stable enough to declare it at beta level, at least. I'll try to find some time to update the README soon, and then I'll close this issue.

**Comment by tejasmanohar** [comment]
Awesome, thanks! No need for updates makes sense- don't see many issues; just wanted to ask since I saw the notice in the README.

**Comment by dano** [comment]
@tejasmanohar I've removed that note from the README (and made a few check-ins). Thanks for poking me!
