### ISSUE TITLE
non-default asyncio loop support not documented

### ISSUE THREAD

**Issue by dmacnet** [dano/aioprocessing#8]
I don't see a way to pass in a non-default asyncio loop to classes like AioQueue. It doesn't look like it accepts a loop kwarg like asyncio.Queue does. How is it done?

**Comment by dano** [comment]
Instead of passing the `loop` kwarg to the constructor of an object, you pass it to the instance methods of the object that run on an event loop.

```python
@asyncio.coroutine
def coro():
    loop = asyncio.new_event_loop()
    q = aioprocessing.AioQueue()
    yield from q.coro_put("some_val", loop=loop)
```

**Comment by dano** [comment]
I added a note to the README about this in https://github.com/dano/aioprocessing/pull/9

**Comment by dano** [comment]
@dmacnet I'm going to close this now that it's documented. Let me know if you still have concerns.
